### ISSUE TITLE
Application Hangs at computer_configurations (similar to issue #8?)

### ISSUE THREAD

**Issue by jaedwards24** [BIG-RAT/Object-Info#11]
I'm consistently seeing the application hang just as it's about to complete. If I click Stop the report text is visible. If I click Export, the exported file is blank. I was unable to copy and paste the report data. 

In version 1.5.0, I see this in the logs:

> Tue Mar 08 08:08:35 [apiCall] endpoint: computer_configurations
> Tue Mar 08 08:08:35 [apiCall] selectedEndpoint: computerconfigurations
> Tue Mar 08 08:08:35 [apiCall] endpointURL: https://[redacted]:8443/JSSResource/computerconfigurations
> Tue Mar 08 08:08:35 [getDetails] completeCounter: 1	apiDetailCount: 1073
> Tue Mar 08 08:08:35 apiCall - existing endpoints: error serializing JSON: nil
> Tue Mar 08 08:08:35 [apiCall] completion - Something went wrong, status code: 404
> Tue Mar 08 08:16:39 [JamfPro.getToken] Attempting to retrieve token from https://[redacted]:8443/api/v1/auth/token.

**The attempting to retrieve token line repeats until I click the Stop button.

In version 1.4.2, I see this in the logs:

> Tue Mar 08 08:30:42 [apiCall] endpoint: computer_configurations
> Tue Mar 08 08:30:42 [apiCall] selectedEndpoint: computerconfigurations
> Tue Mar 08 08:30:42 [apiCall] endpointURL: https://[redacted]:8443/JSSResource/computerconfigurations
> Tue Mar 08 08:30:42 [getDetails] completeCounter: 1	apiDetailCount: 1073
> Tue Mar 08 08:30:42 apiCall - existing endpoints: error serializing JSON: nil
> Tue Mar 08 08:30:42 [apiCall] completion - Something went wrong, status code: 404

**Comment by BIG-RAT** [comment]
What version of Jamf Pro are you running.  Expect I need to handle the computerconfiguration endpoint disappearance.

**Comment by jaedwards24** [comment]
We're running Jamf Pro 10.36.0

**Comment by BIG-RAT** [comment]
Thanks for the heads up - should be resolved in v1.5.2

**Comment by jaedwards24** [comment]
Thanks for making this tool!
