### ISSUE TITLE
Feature Request - Expand Extension Attribute Search

### ISSUE THREAD

**Issue by sdpalmer** [BIG-RAT/Object-Info#14]
Expand Extension Attribute search to include Advanced Searches that use EAs for display purposes only (under the Display tab).

**Comment by sdpalmer** [comment]
Sorry, never mind.  I misread some of the policies it was reporting on and can see that it actually reporting Advanced Searches that only use an EA for display purpose.

**Comment by BIG-RAT** [comment]
Nice catch, I think you were right.  The extension attribute doesn't/didn't show as used if it's only used on the Display tab for Advanced Searches.  Should be fixed in v2.0.1 - thanks.
