### ISSUE TITLE
ObjectInfo appears to be incorrectly detecting Jamf Pro server "Basic authentication" setting

### ISSUE THREAD

**Issue by justintrant** [BIG-RAT/Object-Info#15]
Hello,

After upgrading Jamf Pro to v11.x, ObjectInfo quits when attempting to retrieve data from Jamf Pro. Looking at the logs, I see:
`Tue Jan 23 16:12:38 [JamfPro.getToken] Attempting to retrieve token from https://*redacted*:8443/api/v1/auth/token for version look-up`
`Tue Jan 23 16:12:39 [JamfPro.getToken] new token created for https://*redacted*:8443`
`Tue Jan 23 16:12:39 [JamfPro.getVersion] https://*redacted*:8443 is running v11.1.2-t1702305161`
`Tue Jan 23 16:12:39 [JamfPro.getVersion] https://*redacted*:8443 set to use Basic Authentication`

According to the release notes, ObjectInfo should use bearer tokens when connecting to Jamf Pro 10.35 and above. I'm wondering if the detection of v11.x instances isn't working as expected? Basic authentication has been completely disabled in our Jamf Pro environment.

The same account can request bearer tokens via API call just fine, so it's not a permissions issue.

Thanks in advance!

**Comment by BIG-RAT** [comment]
Version lookup could indeed be failing - needed to fix that on a couple other apps and may have missed it here.  I’ll give it a look shortly, and thanks for the heads up.

**Comment by BIG-RAT** [comment]
v2.0.2 should have this resolved.

**Comment by justintrant** [comment]
Excellent, thanks so much. Easily one of the most useful tools out there for Jamf Pro admin!
