### ISSUE TITLE
Feature Request: Leverage your "standard" server login

### ISSUE THREAD

**Issue by dan-snelson** [BIG-RAT/Object-Info#16]
Happy Monday, Leslie!

I just noticed that Object Info Version 2.0.2 (1) isn't using your "standard" server drop-down list; please consider "standardizing" it.

Thanks for all you do!

**Comment by BIG-RAT** [comment]
Addressed, some time ago... Have to image you've already noticed.

**Comment by BIG-RAT** [comment]
Added in v3.0.0. Can't believe I forgot we chatted about this so long ago...
