### ISSUE TITLE
Download link in README downloads outdated version

### ISSUE THREAD

**Issue by socalledgenius** [BIG-RAT/Object-Info#19]
Download link in README has the wrong tag and downloads an outdated version.  It's currently set to "https://github.com/BIG-RAT/Object-Info/releases/download/current/Object.Info.zip", it should be "https://github.com/BIG-RAT/Object-Info/releases/latest/download/Object.Info.zip"

**Comment by BIG-RAT** [comment]
Nice catch. Should be resolved.
