### ISSUE TITLE
Feature request "Extension Attributes"

### ISSUE THREAD

**Issue by dvreijen** [BIG-RAT/Object-Info#2]
I am a big fan of this tool. Would like to request it also pulls down all Extension Attributes with the linked computer groups.

Gr,

Daniel

**Comment by BIG-RAT** [comment]
Nice idea.  Added computer and mobile device usage.  Checks groups and advanced searches.

**Comment by dvreijen** [comment]
Looking good!!

It only seems to pull the referenced EA though? I have EA's which are not
referenced by any group and would like to clean those up. Any change you
can pull those as well?
I just noticed the same goes for the scripts and packages.

Otherwise, I am very happy with this tool. Makes life a lot easier!!


Gr,
Daniel

**Comment by BIG-RAT** [comment]
Right, the app only reports on items that are scoped/referenced.

Might look at [Prune](https://github.com/BIG-RAT/Prune) to help identify unused items.  And yes adding extension attributes to that app is on the to-do list.
