### ISSUE TITLE
Spelling error in Objects dropdown menu

### ISSUE THREAD

**Issue by socalledgenius** [BIG-RAT/Object-Info#20]
Extension Attributes is misspelled in the Objects dropdown menu:
<img width="965" alt="Screenshot 2024-09-09 at 8 03 32 AM" src="https://github.com/user-attachments/assets/349e169a-9036-48fb-9b8b-9e5d6cb505fc">

**Comment by BIG-RAT** [comment]
Thanks for the heads up. Should be resolved in v3.0.0
