### ISSUE TITLE
App doesn't display computer groups attached to a policy.

### ISSUE THREAD

**Issue by Tmimmie** [BIG-RAT/Object-Info#4]
When selecting Groups > Computer it searches through all policies but does not display any results. Configuration Profiles and Mac App Store apps work fine. 
This appears to be a new issue since Jamf 10.33.0 as it was working fine with 10.32.1.

When executing the app through the terminal there are no visible errors.

**Comment by BIG-RAT** [comment]
Check v1.4.0 - believe it's resolved.

**Comment by Tmimmie** [comment]
Can confirm it now works, thank you!

**Comment by BIG-RAT** [comment]
Good to hear - thanks for the follow-up.
