### ISSUE TITLE
Feature Request:  Include Enabled/Disabled status of Policies

### ISSUE THREAD

**Issue by sdpalmer** [BIG-RAT/Object-Info#6]
For any searches that result in a list of policies being displayed could you please add the Enabled/Disabled status of the policies.  This would be very helpful in allowing us to quickly focus on Enabled policies when deciding which policies to worry about with packages or scripts that we need to cleanup and remove from our Jamf Pro server.

**Comment by BIG-RAT** [comment]
disabled policies will show [disabled] in frequency column - v2.0.0
