### ISSUE TITLE
Getting details for computer_configuration

### ISSUE THREAD

**Issue by ccsben** [BIG-RAT/Object-Info#8]
When running report for Packages and Scripts, the progress is stuck at Getting details for computer_configuration presumably for the Configuration column?
As a result, even though the result seems there with all the other columns all populated, after manually stop getting details for computer_configuration, the exported list txt file is blank.

**Comment by ccsben** [comment]
Thanks for your prompt response. I'm running Object Info version 1.4.0 (1) and our Jamf Pro version is 10.34.1. I do notice we have a configuration in the Computer Management > Configurations. Not sure what it does and whether it has anything to do with this behaviour.

**Comment by BIG-RAT** [comment]
Let me know if things work better with v1.4.2.

**Comment by ccsben** [comment]
Thanks so much Leslie for the very fast response and resolution. It is indeed working now without the error.
